"""Add rating and review

Revision ID: 604a1a6d4953
Revises: f1f5f057bcb0
Create Date: 2026-06-03 12:07:40.303943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604a1a6d4953'
down_revision = 'f1f5f057bcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movies', schema=None) as batch_op:
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
